### ISSUE TITLE
Command 'dagger' not found

### ISSUE THREAD

**Issue by lukemarsden** [samalba/hf-model-ops#2]
This might be a super noob dagger question, but following the [instructions in the README](https://github.com/samalba/hf-model-ops#how-to-run-the-pipelines) on Ubuntu 23.04 gives me:

```
(.venv) luke@floating:~/pd/hf-model-ops$ dagger run python ./ci/deploy_space.py
Command 'dagger' not found, did you mean:
  command 'tagger' from snap tagger (2022.11.2)
See 'snap info <snapname>' for additional versions.
```

`dagger-io` is in the `requirements.txt` that I pip installed inside the virtualenv, so I'd expect if it were to install a CLI tool, it would be in `.venv/bin/` but  there's no such program there. The [getting started docs](https://docs.dagger.io/628381/quickstart-sdk) don't tell me to do anything other than installing the Python SDK, although I feel like there should be a dagger engine install step?

Maybe I just need to `python` run the ci scripts? In which case we should update the readme. Or if installing a `dagger` CLI is necessary, the docs on dagger.io should make that clearer.

**Comment by lukemarsden** [comment]
Update: everything works fine when I just run `python ./ci/deploy_space.py`, so I guess we should just update the README :smile: 

I'm happy to do that if you agree with the approach.

**Comment by samalba** [comment]
Yes, indeed I should add some instructions in the readme. You can run the deploy script directly, however running it using the dagger cli will give you access to a better output.

Here is how to install the cli: https://docs.dagger.io/cli/465058/install

**Comment by lukemarsden** [comment]
Ah, great thanks, don't know why I didn't notice that in the docs 😅
